@extends('owner.layout')
@section('heading','Ringkasan Bisnis')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-4"><div><h4 class="fw-bold mb-1">Selamat datang, {{ $owner->name }}</h4><p class="sub mb-0">Pantau performa dan operasional bisnis kos Anda.</p></div><a href="{{ route('owner.properties') }}" class="btn btn-teal"><i class="bi bi-plus-lg"></i> Tambah Properti</a></div>
<div class="row g-3 mb-4">
@foreach([
 ['owner.properties','bi-houses-fill','Total Properti',$stats['properties']],['owner.rooms','bi-door-fill','Total Kamar',$stats['rooms']],['owner.rooms','bi-person-check-fill','Kamar Terisi',$stats['occupied']],
 ['owner.rooms','bi-door-open-fill','Kamar Kosong',$stats['available']],['owner.bookings','bi-calendar2-plus-fill','Booking Baru',$stats['new_bookings']],['owner.revenue','bi-cash-stack','Pendapatan Bulan Ini','Rp '.number_format($stats['monthly_revenue'],0,',','.')]
] as [$route,$icon,$label,$value])<div class="col-xl-2 col-md-4 col-6"><a class="metric h-100" href="{{ route($route) }}"><span class="icon"><i class="bi {{ $icon }}"></i></span><small>{{ $label }}</small><strong>{{ $value }}</strong></a></div>@endforeach
</div>
<div class="row g-3 mb-4"><div class="col-lg-8"><div class="panel"><div class="d-flex justify-content-between mb-3"><div><div class="section-title">Pendapatan</div><div class="sub">Enam bulan terakhir</div></div><select class="form-select form-select-sm w-auto"><option>Bulanan</option><option>Mingguan</option><option>Tahunan</option></select></div><div class="chart-box"><canvas id="revenueChart"></canvas></div></div></div><div class="col-lg-4"><div class="panel h-100"><div class="section-title">Okupansi Kamar</div><div class="sub mb-3">Status kamar saat ini</div><div class="chart-box"><canvas id="occupancyChart"></canvas></div></div></div></div>
<div class="row g-3"><div class="col-lg-7"><div class="panel"><div class="d-flex justify-content-between mb-3"><div><div class="section-title">Booking Terbaru</div><div class="sub">Terima atau tolak booking secara langsung</div></div><a href="{{ route('owner.bookings') }}" class="btn btn-sm btn-outline-secondary">Lihat Semua</a></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Penyewa</th><th>Properti / Kamar</th><th>Total</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($recentBookings as $booking)<tr id="booking-{{ $booking->id }}"><td><strong>{{ $booking->tenant_name }}</strong><br><span class="sub">{{ $booking->user?->phone }}</span></td><td>{{ $booking->room?->property?->name }}<br><span class="sub">Kamar {{ $booking->room?->room_number }}</span></td><td>Rp {{ number_format($booking->total_amount,0,',','.') }}</td><td><span class="status s-{{ $booking->status }}">{{ $booking->status }}</span></td><td>@if($booking->status==='pending')<div class="actions"><button class="btn btn-sm btn-success booking-action" data-id="{{ $booking->id }}" data-status="approved"><i class="bi bi-check"></i></button><button class="btn btn-sm btn-outline-danger booking-action" data-id="{{ $booking->id }}" data-status="rejected"><i class="bi bi-x"></i></button></div>@endif</td></tr>@empty<tr><td colspan="5" class="text-center sub py-4">Belum ada booking.</td></tr>@endforelse</tbody></table></div></div></div>
<div class="col-lg-5"><div class="panel mb-3"><div class="section-title mb-3">Grafik Booking</div><div class="chart-box"><canvas id="bookingChart"></canvas></div></div><div class="panel"><div class="section-title mb-3">Properti Saya</div>@foreach($properties as $property)<div class="d-flex gap-3 align-items-center border-bottom py-2"><img class="property-img" src="{{ $property->image_url ?: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267' }}"><div class="flex-grow-1"><strong class="small">{{ $property->name }}</strong><div class="sub">{{ $property->occupied_rooms_count }}/{{ $property->rooms_count }} kamar terisi</div></div><span class="status s-active">{{ $property->status }}</span></div>@endforeach</div></div></div>
@endsection
@push('js')<script>
new Chart(document.getElementById('revenueChart'),{type:'line',data:{labels:@json($revenueChart->pluck('label')),datasets:[{data:@json($revenueChart->pluck('value')),borderColor:'#0d9488',backgroundColor:'rgba(13,148,136,.12)',fill:true,tension:.4}]},options:{maintainAspectRatio:false,plugins:{legend:{display:false}}}});
new Chart(document.getElementById('occupancyChart'),{type:'doughnut',data:{labels:['Terisi','Kosong','Booking'],datasets:[{data:[{{ $stats['occupied'] }},{{ $stats['available'] }},{{ max(0,$stats['rooms']-$stats['occupied']-$stats['available']) }}],backgroundColor:['#0d9488','#cbd5e1','#3b82f6']}]},options:{maintainAspectRatio:false}});
new Chart(document.getElementById('bookingChart'),{type:'bar',data:{labels:@json($bookingChart->pluck('label')),datasets:[{data:@json($bookingChart->pluck('value')),backgroundColor:'#0d9488',borderRadius:6}]},options:{maintainAspectRatio:false,plugins:{legend:{display:false}}}});
document.querySelectorAll('.booking-action').forEach(btn=>btn.addEventListener('click',()=>ownerAction(btn)));
async function ownerAction(btn){const status=btn.dataset.status;const answer=await Swal.fire({title:status==='approved'?'Terima Booking?':'Tolak Booking?',icon:'question',showCancelButton:true,confirmButtonText:status==='approved'?'Ya, Terima':'Ya, Tolak'});if(!answer.isConfirmed)return;const res=await fetch(`/owner/bookings/${btn.dataset.id}/status`,{method:'PATCH',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content},body:JSON.stringify({status})});const data=await res.json();if(res.ok){Swal.fire('Berhasil',data.message,'success').then(()=>location.reload())}else Swal.fire('Gagal',data.message||'Aksi gagal','error')}
</script>@endpush
