@extends('owner.layout')
@section('heading', ucfirst($section))
@section('content')
@php $titles=['properties'=>'Properti Saya','rooms'=>'Kamar Kos','bookings'=>'Booking Masuk','tenants'=>'Data Penyewa','payments'=>'Pembayaran Midtrans','revenue'=>'Pendapatan','reports'=>'Laporan Bisnis','notifications'=>'Notifikasi']; @endphp
<div class="d-flex justify-content-between align-items-center mb-4"><div><h4 class="fw-bold mb-1">{{ $titles[$section] ?? ucfirst($section) }}</h4><p class="sub mb-0">Kelola data bisnis kos Anda dari satu tempat.</p></div>@if(in_array($section,['properties','rooms']))<button class="btn btn-teal" data-bs-toggle="modal" data-bs-target="#createModal"><i class="bi bi-plus-lg"></i> Tambah {{ $section==='properties'?'Properti':'Kamar' }}</button>@endif</div>
<div class="panel"><div class="table-responsive"><table class="table align-middle" id="ownerTable"><thead><tr>
@if($section==='properties')<th>Properti</th><th>Lokasi</th><th>Kamar</th><th>Rating</th><th>Status</th><th>Aksi</th>
@elseif($section==='rooms')<th>Kamar</th><th>Properti</th><th>Tipe</th><th>Harga</th><th>Status</th><th>Aksi</th>
@elseif(in_array($section,['bookings','tenants']))<th>Penyewa</th><th>Properti / Kamar</th><th>Periode</th><th>Total</th><th>Status</th><th>Aksi</th>
@elseif(in_array($section,['payments','revenue']))<th>Invoice</th><th>Penyewa</th><th>Properti / Kamar</th><th>Metode</th><th>Total</th><th>Status</th>
@elseif($section==='notifications')<th>Notifikasi</th><th>Pesan</th><th>Waktu</th>
@else<th>Laporan</th><th>Deskripsi</th><th>Aksi</th>@endif
</tr></thead><tbody>
@if($section==='properties')@foreach($items as $item)<tr><td><div class="d-flex gap-2 align-items-center"><img class="property-img" src="{{ $item->image_url ?: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267' }}"><strong>{{ $item->name }}</strong></div></td><td>{{ $item->location }}</td><td>{{ $item->rooms_count }}</td><td><i class="bi bi-star-fill text-warning"></i> {{ $item->rating }}</td><td><span class="status s-active">{{ $item->status }}</span></td><td><button class="btn btn-sm btn-outline-danger delete-item" data-url="{{ route('owner.properties.destroy',$item) }}"><i class="bi bi-trash"></i></button></td></tr>@endforeach
@elseif($section==='rooms')@foreach($items as $item)<tr><td><strong>{{ $item->room_number }}</strong></td><td>{{ $item->property->name }}</td><td>{{ $item->room_type }}</td><td>Rp {{ number_format($item->price_per_month,0,',','.') }}</td><td><select class="form-select form-select-sm room-status" data-url="{{ route('owner.rooms.status',$item) }}">@foreach(['available','booked','occupied'] as $s)<option {{ $item->status===$s?'selected':'' }}>{{ $s }}</option>@endforeach</select></td><td><button class="btn btn-sm btn-outline-danger delete-item" data-url="{{ route('owner.rooms.destroy',$item) }}"><i class="bi bi-trash"></i></button></td></tr>@endforeach
@elseif(in_array($section,['bookings','tenants']))@foreach($items as $item)<tr id="booking-{{ $item->id }}"><td><strong>{{ $item->tenant_name }}</strong><br><span class="sub">{{ $item->user?->phone }}</span></td><td>{{ $item->room?->property?->name }} / {{ $item->room?->room_number }}</td><td>{{ $item->check_in_date?->format('d M Y') ?? '-' }} - {{ $item->check_out_date?->format('d M Y') ?? '-' }}</td><td>Rp {{ number_format($item->total_amount,0,',','.') }}</td><td><span class="status s-{{ $item->status }}">{{ $item->status }}</span></td><td>@if($section==='bookings'&&$item->status==='pending')<button class="btn btn-sm btn-success booking-action" data-id="{{ $item->id }}" data-status="approved">Terima</button> <button class="btn btn-sm btn-outline-danger booking-action" data-id="{{ $item->id }}" data-status="rejected">Tolak</button>@else<a class="btn btn-sm btn-outline-primary" href="https://wa.me/{{ preg_replace('/\D/','',$item->user?->phone) }}">Hubungi</a>@endif</td></tr>@endforeach
@elseif(in_array($section,['payments','revenue']))@foreach($items as $item)<tr><td><strong>{{ $item->invoice_number }}</strong></td><td>{{ $item->tenant_name }}</td><td>{{ $item->booking?->room?->property?->name }} / {{ $item->booking?->room?->room_number }}</td><td>{{ $item->payment_method ?? '-' }}</td><td>Rp {{ number_format($item->gross_amount ?? $item->amount,0,',','.') }}</td><td><span class="status s-{{ $item->payment_status }}">{{ $item->payment_status }}</span></td></tr>@endforeach
@elseif($section==='notifications')@foreach($items as $item)<tr><td><strong>{{ $item->title }}</strong></td><td>{{ $item->message }}</td><td>{{ $item->created_at->diffForHumans() }}</td></tr>@endforeach
@else @foreach([['Laporan Pendapatan PDF','Ringkasan pendapatan berdasarkan periode.'],['Laporan Booking PDF','Daftar dan status seluruh booking.'],['Laporan Penyewa PDF','Data penyewa aktif.'],['Rekap Pembayaran Excel','Rekap transaksi pembayaran Midtrans.']] as [$name,$desc])<tr><td><strong>{{ $name }}</strong></td><td>{{ $desc }}</td><td><button class="btn btn-sm btn-outline-primary" onclick="window.print()"><i class="bi bi-download"></i> Download</button></td></tr>@endforeach @endif
</tbody></table></div>@if(method_exists($items,'links')){{ $items->links('pagination::bootstrap-5') }}@endif</div>
@if($section==='properties')<div class="modal fade" id="createModal"><div class="modal-dialog"><form class="modal-content" method="post" action="{{ route('owner.properties.store') }}">@csrf<div class="modal-header"><h5>Tambah Properti</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body">@foreach(['name'=>'Nama Properti','location'=>'Lokasi','city'=>'Kota','province'=>'Provinsi','image_url'=>'URL Foto'] as $name=>$label)<label class="form-label small">{{ $label }}</label><input class="form-control mb-2" name="{{ $name }}" {{ in_array($name,['name','location'])?'required':'' }}>@endforeach<input type="hidden" name="status" value="active"></div><div class="modal-footer"><button class="btn btn-teal">Simpan</button></div></form></div></div>
@elseif($section==='rooms')<div class="modal fade" id="createModal"><div class="modal-dialog"><form class="modal-content" method="post" action="{{ route('owner.rooms.store') }}">@csrf<div class="modal-header"><h5>Tambah Kamar</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><select class="form-select mb-2" name="property_id" required>@foreach($properties as $p)<option value="{{ $p->id }}">{{ $p->name }}</option>@endforeach</select>@foreach(['room_number'=>'Nomor Kamar','room_type'=>'Tipe Kamar','price_per_month'=>'Harga per Bulan','capacity'=>'Kapasitas'] as $name=>$label)<input class="form-control mb-2" name="{{ $name }}" placeholder="{{ $label }}" required>@endforeach<select class="form-select" name="status"><option>available</option><option>booked</option><option>occupied</option></select></div><div class="modal-footer"><button class="btn btn-teal">Simpan</button></div></form></div></div>@endif
@endsection
@push('js')<script>
const token=document.querySelector('meta[name=csrf-token]').content;
document.querySelectorAll('.booking-action').forEach(b=>b.onclick=async()=>{let a=await Swal.fire({title:b.dataset.status==='approved'?'Terima Booking?':'Tolak Booking?',showCancelButton:true,icon:'question'});if(!a.isConfirmed)return;let r=await fetch(`/owner/bookings/${b.dataset.id}/status`,{method:'PATCH',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':token},body:JSON.stringify({status:b.dataset.status})});let d=await r.json();Swal.fire(r.ok?'Berhasil':'Gagal',d.message||'Aksi gagal',r.ok?'success':'error').then(()=>r.ok&&location.reload())});
document.querySelectorAll('.room-status').forEach(s=>s.onchange=()=>fetch(s.dataset.url,{method:'PATCH',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':token},body:JSON.stringify({status:s.value})}));
document.querySelectorAll('.delete-item').forEach(b=>b.onclick=async()=>{let a=await Swal.fire({title:'Hapus data?',showCancelButton:true,icon:'warning'});if(!a.isConfirmed)return;let r=await fetch(b.dataset.url,{method:'DELETE',headers:{'X-CSRF-TOKEN':token}});let d=await r.json();Swal.fire(r.ok?'Berhasil':'Gagal',d.message||'Aksi gagal',r.ok?'success':'error').then(()=>r.ok&&location.reload())});
</script>@endpush
